# Generated by Django 4.2.1 on 2023-05-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(verbose_name='Date Played'),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
